// alert('hell0')
// prompt("hey enter your name");

// alert(3456432);
// alert("2323");
// alert(true);
// alert(false);

// console.log("hello demo");
// console.log(478364);
// console.log(true);
// console.log(false);

// document.write("hello");
// document.write(3746);
// document.write(true);
// document.write(false);

var user_name="ram";
var user_age=34;
document.write(user_name);
document.write(user_age);

alert(user_name);
alert(user_age);

// console.log(user_name);
// console.log(user_age);

// //my  name is john and age is 12

// document.write("my name is "+user_name+" and age is"+user_age);

// var x="hey";
// var y="how are you"
// document.write(x+" "+y);


